name: 'Version Has Changed'
description: 'Checks your Package.json file and sees if its changed. WIP'
author: 'RockiRider'
inputs:
  from:
    required: true
    description: 'Start of the commit range to check (can be a commit hash or a branch name).'
  to:
    required: false
    description: 'End of the commit range to check (can be a commit hash or branch). If not provided, will be the current commit of the head branch on a `pull_request` event. For a push event, it will be the current commit of the current branch.'
  path:
    required: false
    description: 'Path to the package.json to '
    default: './'

outputs:
  changed:
    description: 'True if the package.json version changed, otherwise false.'
runs:
  using: 'node16'
  main: 'dist/index.js'
