name: 'Has Version Changed'
description: 'Checks your Package.json file and sees if its changed.'
author: 'Octopus Money'
inputs:
  from:
    required: true
    description: 'Start of the commit range to check (can be a commit hash or a branch name).'
  to:
    required: true
    description: 'End of the commit range to check (can be a commit hash or branch). If not provided, will be the current commit of the head branch on a `pull_request` event. For a push event, it will be the current commit of the current branch.'
  path:
    required: false
    description: 'Path to the package.json to '
    default: './'
  match:
    required: false
    description: 'Global pattern to check for multiple package.json changes'
    default: ''

outputs:
  changed:
    description: 'True if any package.json version changed, otherwise false.'
  matched:
    description: 'JSON encoded array of any found version bumps'
runs:
  using: 'node24'
  main: 'dist/index.js'
